import 'package:flutter/material.dart';
import '../../../features/news/domain/media_source.dart';

class MediaSources {
  MediaSources._();

  static const List<MediaSource> all = [
    MediaSource(
      id: 'zoomeco',
      name: 'Zoomeco',
      feedUrl: 'https://zoom-eco.net/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Économie', 'Finance'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF1565C0),
    ),
    MediaSource(
      id: 'okapinews',
      name: 'OkapiNews',
      feedUrl: 'https://okapinews.net/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Actualités', 'Culture'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF6A1B9A),
    ),
    MediaSource(
      id: 'actu30',
      name: 'Actu30',
      feedUrl: 'https://actu30.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Politique', 'Société'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFFC62828),
    ),
    MediaSource(
      id: 'infoscd',
      name: 'InfosCD',
      feedUrl: 'https://infos.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Politique', 'Sécurité'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF283593),
    ),
    MediaSource(
      id: 'scooprdc',
      name: 'ScoopRDC',
      feedUrl: 'https://scooprdc.net/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Actualités', 'Sport'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF00695C),
    ),
    MediaSource(
      id: 'footrdc',
      name: 'FootRDC',
      feedUrl: 'https://footrdc.com/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Sport'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF2E7D32),
    ),
    MediaSource(
      id: 'reveilcongo',
      name: 'Réveil Congo',
      feedUrl: 'https://reveil-congo.net/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Société', 'Politique'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFFE65100),
    ),
    MediaSource(
      id: 'radiookapi',
      name: 'Radio Okapi',
      feedUrl: 'https://radiookapi.net/feed/actualite',
      feedType: FeedType.rss,
      categories: ['Actualités', 'Société'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF4527A0),
    ),
    MediaSource(
      id: 'iwacu',
      name: 'Iwacu',
      feedUrl: 'https://iwacu-burundi.org/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['International'],
      country: 'BI',
      logoUrl: '',
      color: Color(0xFF006064),
    ),
    MediaSource(
      id: 'congopress',
      name: 'Congo Press',
      feedUrl: 'https://congo-press.com/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Économie', 'Culture'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF4E342E),
    ),
    MediaSource(
      id: 'nouvellecd',
      name: 'NouvelleCD',
      feedUrl: 'https://nouvelle.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Politique', 'Santé'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFFAD1457),
    ),
    MediaSource(
      id: 'grandslacs',
      name: 'Grands Lacs',
      feedUrl: 'https://grandslacsnews.com/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['International'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF37474F),
    ),
    MediaSource(
      id: 'infos27',
      name: 'Infos27',
      feedUrl: 'https://infos27.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Actualités', 'Politique'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF0D47A1),
    ),
    MediaSource(
      id: 'opinioninfo',
      name: 'Opinion Info',
      feedUrl: 'https://www.opinion-info.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Politique', 'Diplomatie', 'Justice'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF1B5E20),
    ),
    MediaSource(
      id: 'doseco',
      name: 'DosEco',
      feedUrl: 'https://doseco.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Économie', 'Finances', 'Mines'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF004D40),
    ),
    MediaSource(
      id: 'unecd',
      name: 'UNE.CD',
      feedUrl: 'https://www.une.cd/wp-json/wp/v2/posts?per_page=30',
      feedType: FeedType.wordpress,
      categories: ['Politique', 'Sécurité', 'Société'],
      country: 'CD',
      logoUrl: '',
      color: Color(0xFF4A148C),
    ),
  ];

  static MediaSource? findById(String id) {
    try {
      return all.firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }
}
